ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS marina_address TEXT,
  ADD COLUMN IF NOT EXISTS marina_vhf TEXT,
  ADD COLUMN IF NOT EXISTS marina_phone TEXT,
  ADD COLUMN IF NOT EXISTS marina_email TEXT,
  ADD COLUMN IF NOT EXISTS marina_checkin TEXT,
  ADD COLUMN IF NOT EXISTS marina_checkout TEXT,
  ADD COLUMN IF NOT EXISTS marina_coordinates TEXT,
  ADD COLUMN IF NOT EXISTS flag TEXT,
  ADD COLUMN IF NOT EXISTS client_phone TEXT;

ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS phone TEXT;